name: Update Blog Metadata

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  generate-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for git history
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Generate metadata.json
        run: |
          python .github/scripts/update_metadata.py

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Configure GitHub auth
          git remote set-url origin "https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git"

          # Add and commit changes (metadata.json + tags.json)
          git add metadata.json tags.json
          # If there's a diff, commit and push
          git diff --quiet && git diff --staged --quiet || \
            (git commit -m "Auto-update metadata and tags" && git push origin HEAD:main)
